package PracticeTest1;
import java.io.FileNotFoundException;
import java.io.IOException;

public class q8 {
//    public static void main(String [ ] args) {
//        try {
//            method ();
//        } catch(IOException e) { // error here
//            System.out.println("caught");
//        }
//    }
//
//    public static IOException method() {
//        try {
//            return new IOException();
//        } catch(FileNotFoundException e) { // error here
//            return new FileNotFoundException();
//        }
//    }
//Option D is the correct answer.
//
//    In the given code, at line 16, in method(), complier sees that there is no way of throwing a FileNotFoundException in the try block. Hence, catch block becomes unreachable code. So, the code fails to compile. Thus, option D is correct.
//
//    REFERENCE : http://docs.oracle.com/javase/tutorial/essential/exceptions/catch.htm
}
